### ISSUE TITLE
Build error under Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [jenslody/aeskulap#12]
This happens under Arch Linux:

In file included from imagepool.h:25,
                 from dicomdir.cpp:22:
poolinstance.h:46:81: Fehler: »void ImagePool::remove_instance(const Glib::RefPtr<ImagePool::Instance>&)« sollte innerhalb von »ImagePool« deklariert werden
  friend void ImagePool::remove_instance(const Glib::RefPtr<ImagePool::Instance>&);
                                                                                 ^
make[2]: *** [Makefile:607: dicomdir.lo] Error 1
make[2]: Leaving directory '/home/haawda/paketierung/meine_Pakete/aeskulap/src/aeskulap-release-0-2-2-beta2/imagepool'
make[1]: *** [Makefile:495: all-recursive] Error 1
make[1]: Leaving directory '/home/haawda/paketierung/meine_Pakete/aeskulap/src/aeskulap-release-0-2-2-beta2'
make: *** [Makefile:427: all] Error 2

I think this is related to Arch's switch to gcc 8.1.0, under 6.4.1 it builds fine. Unfortunately Arch does no longer ship old gcc versions.

**Comment by kolewu** [comment]
This is already fixed on master with commit 8787e9522a0dc7146d12b548089be23de2e7d59b

**Comment by jenslody** [comment]
Should be fixed in ce82f856868f7a3217fff714d0de5ee8b6cf3aa2
